#Download file first

In [ ]:
! gdown https://drive.google.com/uc?id=1F3Zsb6zEdu-yKyrHi3RzpCm9g3M6Vmr5

Downloading...
From: https://drive.google.com/uc?id=1F3Zsb6zEdu-yKyrHi3RzpCm9g3M6Vmr5
To: /content/text_data.csv
100% 2.51M/2.51M [00:00<00:00, 23.2MB/s]


#Read Data

In [ ]:
import pandas as pd

df=pd.read_csv('text_data.csv')
df.dropna(inplace=True)

In [ ]:
df

message             class
0               อย่า โกรธ แม่ ขาย 😭😭 ดู ย้อนหลัง ที่นี่   CH3Thailand.csv
1      แอคชั่น เต็ม แถม ซึ้ง ฉาก หวาน ดู เบื้องหลัง ...   CH3Thailand.csv
2      ร้องไห้ ไหว ทด กลายเป็น ทาส เด็ก ดู ย้อนหลัง ...   CH3Thailand.csv
3      รื้อ กระเป๋า เผ่า ส่อง  ไอเทม เด็ด ดู ติดตาม ...   CH3Thailand.csv
4      มีความผิด ที่จะ โดน เฆี่ยน ทด ใจเด็ด  ดู ย้อน...   CH3Thailand.csv
...                                                 ...               ...
4550   คุ้ม คุ้ม คุ้ม แบ่งปัน ส่วนลด โปรโมชั่น บัตรเ...  punpromotion.csv
4551   Mo-Mo Paradise กิน อั้น ชาบู ชาบู สุกี้ สไตล์...  punpromotion.csv
4552    บัตรเครดิต ส่วนลด ไม่ต้อง เสียใจ ปัน โปร >> ...  punpromotion.csv
4553           เบื่อ ไหม พลาด ส่วนลด บัตรเครดิต ปัน โปร  punpromotion.csv
4554   แบ่งปัน ส่วนลด โปรโมชั่น บัตรเครดิต ร้านอาหาร...  punpromotion.csv

[4554 rows x 2 columns]

In [ ]:
pos_data=df['message']
pos_target=df['class']

# Train and Test Using train_test_split()

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

from sklearn.model_selection import train_test_split

vectorizer=CountVectorizer(tokenizer=lambda x: x.split())
tfidf=TfidfTransformer()
X=vectorizer.fit_transform(pos_data)
X=tfidf.fit_transform(X)
X_train, X_test, Y_train, Y_test = train_test_split(X,pos_target, test_size = 0.10, random_state = 42)
clf=MultinomialNB().fit(X_train,Y_train)
Y_predict = clf.predict(X_test)
accuracy_score(Y_test, Y_predict)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


0.9802631578947368

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

show_pos_data=['i buy a pet book i want to find the best food for dog and cat','i buy food for my dog at the pet shop','the dog and the cat']
vectorizer=CountVectorizer()
tfidf=TfidfTransformer()
X=vectorizer.fit_transform(show_pos_data)
Y=tfidf.fit_transform(X)
X

<3x16 sparse matrix of type '<class 'numpy.int64'>'
	with 26 stored elements in Compressed Sparse Row format>

In [ ]:
X.todense()

matrix([[1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1],
        [0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0]])

In [ ]:
vectorizer.get_feature_names_out()

array(['and', 'at', 'best', 'book', 'buy', 'cat', 'dog', 'find', 'food',
       'for', 'my', 'pet', 'shop', 'the', 'to', 'want'], dtype=object)

In [ ]:
X.todense()

matrix([[1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1],
        [0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0]])

In [ ]:
Y.todense()

matrix([[0.25117442, 0.        , 0.33026418, 0.33026418, 0.25117442,
         0.25117442, 0.19505935, 0.33026418, 0.25117442, 0.25117442,
         0.        , 0.25117442, 0.        , 0.19505935, 0.33026418,
         0.33026418],
        [0.        , 0.40786601, 0.        , 0.        , 0.31019261,
         0.        , 0.24089223, 0.        , 0.31019261, 0.31019261,
         0.40786601, 0.31019261, 0.40786601, 0.24089223, 0.        ,
         0.        ],
        [0.44652407, 0.        , 0.        , 0.        , 0.        ,
         0.44652407, 0.34676577, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.69353155, 0.        ,
         0.        ]])

In [ ]:
vectorizer.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['and',
 'at',
 'best',
 'book',
 'buy',
 'cat',
 'dog',
 'find',
 'food',
 'for',
 'my',
 'pet',
 'shop',
 'the',
 'to',
 'want']

# Cross Validation

In [ ]:
from sklearn.model_selection import cross_val_score
cv=cross_val_score(clf,X,pos_target,cv=10)

In [ ]:
cv

array([0.94736842, 0.9495614 , 0.97807018, 0.98026316, 0.99340659,
       0.99340659, 0.98461538, 0.98901099, 0.98681319, 0.96703297])

In [ ]:
sum(cv)/10

0.9769548872180451

In [ ]:
docs_new = ['เปิด ดู ละคร ดัง ตอนนี้','ลด ร้าน ดัง วันนี้ ด่วน']
X_new = vectorizer.transform(docs_new)
X_new = tfidf.transform(X_new)
predicted = clf.predict(X_new)
print(predicted)

['CH3Thailand.csv' 'punpromotion.csv']


# Using Pipeline

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

df=pd.read_csv('text_data.csv')
df.dropna(inplace=True)
pos_data=df['message']
pos_target=df['class']

clf_pipeline = Pipeline([('vect',CountVectorizer(tokenizer=lambda x: x.split())),
                         ('tfidf',TfidfTransformer()),
                         ('clf',MultinomialNB())])
clf_pipeline.fit(pos_data,pos_target)

/usr/local/lib/python3.9/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


Pipeline(steps=[('vect',
                 CountVectorizer(tokenizer=<function <lambda> at 0x7ff9b1af5430>)),
                ('tfidf', TfidfTransformer()), ('clf', MultinomialNB())])

In [ ]:
docs_new = ['เปิด ดู ละคร ดัง ตอนนี้','ลด ร้าน ดัง วันนี้ ด่วน']
clf_pipeline.predict(docs_new)

array(['CH3Thailand.csv', 'punpromotion.csv'], dtype='<U16')